name: flutter_getx_retrofit_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get: 4.6.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  retrofit: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  lints: 1.0.1
  retrofit_generator: ^3.0.0+2

flutter:
  uses-material-design: true
